dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
enabled: true
useGitignore: true
ignorePaths:
  - .config/requirements*
  - \.*
  - cspell.config.yaml
  - uv.lock

  - "*.egg-info"

languageSettings:
  - languageId: python
    allowCompoundWords: false
